base: 'https://blockchaintogo.de'
languages:
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UFT8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: English
    hreflang: en_US.UTF8
    direction: ''
    flag: us
    languageId: 0
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: de_DE.UTF8
    direction: ''
    fallbackType: strict
    fallbacks: '0'
    flag: de
    languageId: 1
rootPageId: 56
websiteTitle: BlockChainToGo
